cd ~/proneural/chip-seq

count_lines() {
  wc -l < "$1.bed"
}

rm line_counts.tsv

# Print the table with line counts to a TSV file
output_file="line_counts.tsv"

{
  echo -e "GSE Accession\tGenome\tStudy Name\tReplicate 1\tReplicate 2\tReplicate 3\tReplicate 4\tReplicate 5\tReplicate 6"
  echo -e "matsuda_neurod1_microglia\t$(count_lines GSM2800529)"
  echo -e "pataskar_neurod1_mesc\t$(count_lines GSM1586779)\t$(count_lines GSM1586780)"
  echo -e "kim_neurod1_hek_treatment_pcag\t$(count_lines GSM7213735)"
  echo -e "fong_neurod2_p19\t$(count_lines GSM857389)"
  echo -e "fong_neurod2_mef\t$(count_lines GSM857392)"
  echo -e "fong_neurod2_p19_control\t$(count_lines GSM1575852)\t$(count_lines GSM1575853)"
  echo -e "fong_neurod2_p19_treatment\t$(count_lines GSM1575850)\t$(count_lines GSM1575851)"
  echo -e "aydin_neurog2_eb_treatment_12h\t$(count_lines GSM3136832)\t$(count_lines GSM3136833)\t$(count_lines GSM3136834)"
  echo -e "aydin_neurog2_eb_treatment_48h\t$(count_lines GSM3136849)\t$(count_lines GSM3136850)"
  echo -e "velasco_neurog2_eb_treatment_12h\t$(count_lines GSM2124210)\t$(count_lines GSM2124211)"
  echo -e "smith_neurog2_mrc5_treatment_05dpt\t$(count_lines GSM1970150)\t$(count_lines GSM1970151)"
  echo -e "smith_neurog2_mrc5_treatment_1dpt\t$(count_lines GSM1970152)\t$(count_lines GSM1970153)"
  echo -e "smith_neurog2_mrc5_treatment_2dpt\t$(count_lines GSM1970154)\t$(count_lines GSM1970155)"
  echo -e "vainorius_neurog2_mesc\t$(count_lines GSM6266267)\t$(count_lines GSM6266268)\t$(count_lines GSM6266270)\t$(count_lines GSM6266271)"
  echo -e "pereira_neurog2_astrocytes\t$(count_lines GSM6368738)\t$(count_lines GSM6368739)\t$(count_lines GSM6368740)"
  echo -e "pereira_neurog2_astrocytes_yy+\t$(count_lines GSM8242624)\t$(count_lines GSM8242625)"
  echo -e "pereira_neurog2_astrocytes_yy-\t$(count_lines GSM8242622)\t$(count_lines GSM8242623)"
  echo -e "li_twist2_myoblast_dm_control\t$(count_lines GSM3659993)"
  echo -e "li_twist2_myoblast_dm_treatment\t$(count_lines GSM3660010)\t$(count_lines GSM3660011)"
  echo -e "li_twist2_myoblast_gm_control\t$(count_lines GSM3659985)\t$(count_lines GSM3659986)"
  echo -e "li_twist2_myoblast_gm_treatment\t$(count_lines GSM3660001)\t$(count_lines GSM3660002)"
  echo -e "fan_twist1_eb_control\t$(count_lines GSM3734509)\t$(count_lines GSM3734510)"
  echo -e "fan_twist1_eb_treatment\t$(count_lines GSM3734511)\t$(count_lines GSM3734512)\t$(count_lines GSM3734513)\t$(count_lines GSM3734514)"
  echo -e "yu_twist1_mcf7_control\t$(count_lines GSM5708358)"
  echo -e "yu_twist1_mcf7_treatment\t$(count_lines GSM5708359)"
  echo -e "lee_twist1_bmsc_control\t$(count_lines GSM6828924)"
  echo -e "lee_twist1_bmsc_treatment\t$(count_lines GSM6828926)"
  echo -e "kim_twist1_hek_treatment_pcag\t$(count_lines GSM7213605)"
  echo -e "kim_twist1_hek_treatment_pcdna\t$(count_lines GSM7213721)\t$(count_lines GSM7213733)\t$(count_lines GSM7857134)\t$(count_lines GSM7857162)"
  echo -e "mazzoni_olig2_mesc\t$(count_lines GSM766059)"
  echo -e "costa_atoh1_mesc\t$(count_lines GSM4059027)\t$(count_lines GSM4059005)"
  echo -e "liu_atoh8_lungcarcinoma\t$(count_lines GSM5712744)"
  echo -e "lin_mesp1_mesc_treatment_12h\t$(count_lines GSM5026170)"
  echo -e "lin_mesp1_mesc_treatment_24h\t$(count_lines GSM5026171)"
  echo -e "chalamalasetty_msgn1_eb\t$(count_lines GSM1332768)"
  echo -e "hershbach_myod1_mef\t$(count_lines GSM6423057)\t$(count_lines GSM6423061)"
  echo -e "fong_myod1_p19\t$(count_lines GSM857390)"
  echo -e "fong_myod1_mef\t$(count_lines GSM857391)"
  echo -e "casey_myod1_mesc\t$(count_lines GSM2576039)"
  echo -e "lee_myod1_mef\t$(count_lines GSM3598008)\t$(count_lines GSM3598009)\t$(count_lines GSM3598010)"
  echo -e "lee_myod1_mesc\t$(count_lines GSM4160356)"
  echo -e "conerly_myod1_mef\t$(count_lines GSM1954031)"
  echo -e "manandhar_myod1_fibroblasts\t$(count_lines GSM2449232)\t$(count_lines GSM2449233)\t$(count_lines GSM2449233)"
  echo -e "conerly_myf5_mef\t$(count_lines GSM1954032)"
  echo -e "casey_ascl1_mesc\t$(count_lines GSM2576033)"
  echo -e "aydin_ascl1_eb_treatment_12h\t$(count_lines GSM3136828)\t$(count_lines GSM3136829)\t$(count_lines GSM3136830)"
  echo -e "aydin_ascl1_eb_treatment_48h\t$(count_lines GSM3136839)\t$(count_lines GSM3136840)"
  echo -e "lee_ascl1_mesc\t$(count_lines GSM4160355)"
  echo -e "lee_ascl1_mef\t$(count_lines GSM3598002)\t$(count_lines GSM3598003)\t$(count_lines GSM3598004)"
  echo -e "wapinski_ascl1_mef\t$(count_lines GSM1187221)"
  echo -e "wapinski_ascl1_npc\t$(count_lines GSM1187228)"
  echo -e "park_ascl1_glioblastoma_control\t$(count_lines GSM2335528)\t$(count_lines GSM2335529)\t$(count_lines GSM2335530)"
  echo -e "park_ascl1_glioblastoma_treatment\t$(count_lines GSM2335531)\t$(count_lines GSM2335532)\t$(count_lines GSM2335533)"
  echo -e "vainorius_ascl1_mesc\t$(count_lines GSM6266261)\t$(count_lines GSM6266262)\t$(count_lines GSM6266264)\t$(count_lines GSM6266265)"
  echo -e "woods_ascl1_neuroblastoma_wt31_treatment\t$(count_lines GSM4654869)\t$(count_lines GSM4654870)\t$(count_lines GSM4654871)\t$(count_lines GSM4654872)"
  echo -e "woods_ascl1_neuroblastoma_wt51_control\t$(count_lines GSM4654885)\t$(count_lines GSM4654886)\t$(count_lines GSM4654887)"
  echo -e "woods_ascl1_neuroblastoma_wt51_treatment\t$(count_lines GSM4654873)\t$(count_lines GSM4654874)\t$(count_lines GSM4654875)\t$(count_lines GSM4654876)"
  echo -e "wang_ascl1_gi-men\t$(count_lines GSM6616013)"
  echo -e "joung_ascl1_hesc\t$(count_lines GSM6674604)"
  echo -e "raposo_ascl1_ns5\t$(count_lines ERR453843)"
  echo -e "casey_ascl2_mesc\t$(count_lines GSM2576036)"
  echo -e "liu_ascl2_cd4_control\t$(count_lines GSM1276937)"
  echo -e "liu_ascl2_cd4_treatment\t$(count_lines GSM1276938)"
  echo -e "jain_tcf4_sudhl\t$(count_lines GSM3375345)"
  echo -e "jain_tcf4_tmd8\t$(count_lines GSM3375347)"
  echo -e "lorenzin_myc_u2os_control\t$(count_lines GSM2050640)"
  echo -e "lorenzin_myc_u2os_treatment\t$(count_lines GSM2050639)"
  echo -e "soufi_myc_bj_control\t$(count_lines GSM1000576)"
  echo -e "soufi_myc_bj_treatment\t$(count_lines GSM896988)"
  echo -e "lin_myc_p493-6_control\t$(count_lines GSM894059)"
  echo -e "lin_myc_p493-6_treatment_1h\t$(count_lines GSM894060)"
  echo -e "lin_myc_p493-6_treatment_24h\t$(count_lines GSM894058)"
  echo -e "see_myc_u2os_lowmyc\t$(count_lines GSM5018585)\t$(count_lines GSM5018586)"
  echo -e "see_myc_u2os_highmyc\t$(count_lines GSM5018587)\t$(count_lines GSM5018588)"
  echo -e "walz_myc_u2os_control\t$(count_lines GSM1231598)"
  echo -e "walz_myc_u2os_treatment\t$(count_lines GSM1231597)"
  echo -e "kress_myc_liver_control\t$(count_lines GSM1973344)\t$(count_lines GSM1973345)\t$(count_lines GSM1973346)\t$(count_lines GSM1973347)"
  echo -e "kress_myc_liver_treatment\t$(count_lines GSM1973348)\t$(count_lines GSM1973349)\t$(count_lines GSM1973350)\t$(count_lines GSM1973351)\t$(count_lines GSM1973352)\t$(count_lines GSM1973353)"
  echo -e "barfeld_myc_lncap_control\t$(count_lines GSM1907203)\t$(count_lines GSM1907204)"
  echo -e "barfeld_myc_lncap_treatment\t$(count_lines GSM1907205)\t$(count_lines GSM1907206)"
  echo -e "croci_myc_liver_control\t$(count_lines GSM2220066)"
  echo -e "croci_myc_liver_treatment\t$(count_lines GSM2220064)"
  echo -e "croci_myc_mef\t$(count_lines GSM2220154)"
  echo -e "sabo_myc_mef_control\t$(count_lines GSM1234508)"
  echo -e "sabo_myc_mef_treatment\t$(count_lines GSM1234509)"
  echo -e "sabo_myc_lymphoblastoma_lowmyc\t$(count_lines GSM1234500)"
  echo -e "sabo_myc_lymphoblastoma_highmyc\t$(count_lines GSM1234501)"
  echo -e "sabo_myc_lymphoblastoma_control\t$(count_lines GSM1234499)"
  echo -e "sabo_myc_lymphoblastoma_treatment_1h\t$(count_lines GSM1386342)"
  echo -e "sabo_myc_lymphoblastoma_treatment_24h\t$(count_lines GSM1386343)"
  echo -e "depretis_myc_mef_control\t$(count_lines GSM2595124)"
  echo -e "depretis_myc_mef_treatment_10min\t$(count_lines GSM2595125)"
  echo -e "depretis_myc_mef_treatment_20min\t$(count_lines GSM2595126)"
  echo -e "depretis_myc_mef_treatment_30min\t$(count_lines GSM2595127)"
  echo -e "depretis_myc_mef_treatment_2h\t$(count_lines GSM2595128)"
  echo -e "depretis_myc_mef_treatment_4h\t$(count_lines GSM2595129)"
  echo -e "muthalagu_myc_mcf10a\t$(count_lines GSM1423725)"
  echo -e "tameire_myc_colorectaladenocarcinoma\t$(count_lines GSM3289768)\t$(count_lines GSM3289769)"
  echo -e "jaenicke_myc_imec\t$(count_lines GSM1715545)"
  echo -e "liang_myc_h2171\t$(count_lines GSM3073948)"
  echo -e "thomas_myc_hek_control\t$(count_lines GSM1493025)\t$(count_lines GSM1493020)\t$(count_lines GSM1493017)"
  echo -e "thomas_myc_hek_treatment\t$(count_lines GSM1493021)\t$(count_lines GSM1493018)"
  echo -e "jung_myc_u2os_control\t$(count_lines GSM2049318)"
  echo -e "jung_myc_u2os_treatment\t$(count_lines GSM2049319)"
  echo -e "zeid_mycn_shep_control\t$(count_lines GSM2572343)"
  echo -e "zeid_mycn_shep_treatment_2h\t$(count_lines GSM2572346)"
  echo -e "zeid_mycn_shep_treatment_6h\t$(count_lines GSM2572349)"
  echo -e "upton_mycn_lan5\t$(count_lines GSM4104628)"
  echo -e "upton_mycn_nb1643\t$(count_lines GSM4104630)"
  echo -e "upton_mycn_cogn415\t$(count_lines GSM4104624)"
  echo -e "bosse_mycn_ngp\t$(count_lines GSM2482828)"
  echo -e "bosse_mycn_kelly\t$(count_lines GSM2482829)"
  echo -e "bosse_mycn_nb1643\t$(count_lines GSM2482830)"
  echo -e "herold_mycn_shep_control\t$(count_lines GSM3044605)"
  echo -e "herold_mycn_shep_treatment\t$(count_lines GSM3044606)"
  echo -e "neikes_mycmax_mcf7_treatment_0001nm\t$(count_lines GSM5814092)"
  echo -e "neikes_mycmax_mcf7_treatment_0010nm\t$(count_lines GSM5814093)"
  echo -e "neikes_mycmax_mcf7_treatment_0100nm\t$(count_lines GSM5814094)"
  echo -e "neikes_mycmax_mcf7_treatment_1000nm\t$(count_lines GSM5814095)"
  echo -e "louphrasitthiphol_mitf_melanoma_control\t$(count_lines GSM4080875)\t$(count_lines GSM4080876)"
  echo -e "louphrasitthiphol_mitf_melanoma_treatment\t$(count_lines GSM4080877)\t$(count_lines GSM4080878)"
  echo -e "weber_hey1_cardiomyocytes_control\t$(count_lines GSM1486068)"
  echo -e "weber_hey1_cardiomyocytes_treatment\t$(count_lines GSM1486069)"
  echo -e "weber_hey1_mesc_control\t$(count_lines GSM1486064)"
  echo -e "weber_hey1_mesc_treatment\t$(count_lines GSM1486065)"
  echo -e "weber_hey2_cardiomyocytes_control\t$(count_lines GSM1486070)"
  echo -e "weber_hey2_cardiomyocytes_treatment\t$(count_lines GSM1486071)"
  echo -e "weber_hey2_mesc_control\t$(count_lines GSM1486066)"
  echo -e "weber_hey2_mesc_treatment\t$(count_lines GSM1486067)"
  echo -e "shang_hes1_mesc\t$(count_lines GSM2049387)"
  echo -e "sugita_hes1_chrondrocytes\t$(count_lines GSM1463456)"
  echo -e "letourneau_sim2_mesc_a6\t$(count_lines GSM1436059)"
  echo -e "letourneau_sim2_mesc_b8\t$(count_lines GSM1436061)"
  echo -e "letourneau_sim2_mesc_c4\t$(count_lines GSM1436063)"
  echo -e "letourneau_sim2_mesc_eb3\t$(count_lines GSM1436065)"
  echo -e "gambardella_tfeb_hek_treatment_18h\t$(count_lines GSM2589820)\t$(count_lines GSM2589821)"
  echo -e "gambardella_tfeb_hek_treatment_36h\t$(count_lines GSM2589822)\t$(count_lines GSM2589823)"
  echo -e "gambardella_tfeb_hek_treatment_90h\t$(count_lines GSM2589824)\t$(count_lines GSM2589825)"
  echo -e "tai-nagara_tfe3_hk-2\t$(count_lines GSM4012629)\t$(count_lines GSM4012630)"
  echo -e "emming_bhlhe40_jurkat_control_clone1\t$(count_lines GSM3488959)"
  echo -e "emming_bhlhe40_jurkat_treatment_clone1\t$(count_lines GSM3488957)"
  echo -e "emming_bhlhe40_jurkat_control_clone2\t$(count_lines GSM3488960)"
  echo -e "emming_bhlhe40_jurkat_treatment_clone2\t$(count_lines GSM3488958)"

} > "$output_file"


# aqui lo he dejado

count_lines_confidence() {
    wc -l < *$1_confidence.bed >> confidence_counts.txt
}

rm confidence_counts.txt


count_lines_confidence "matsuda_neurod1_microglia"
count_lines_confidence "pataskar_neurod1_mesc"
count_lines_confidence "kim_neurod1_hek_treatment_pcag"
count_lines_confidence "fong_neurod2_p19"
count_lines_confidence "fong_neurod2_mef"
count_lines_confidence "fong_neurod2_p19_control"
count_lines_confidence "fong_neurod2_p19_treatment"
count_lines_confidence "aydin_neurog2_eb_treatment_12h"
count_lines_confidence "aydin_neurog2_eb_treatment_48h"
count_lines_confidence "velasco_neurog2_eb_treatment_12h"
count_lines_confidence "smith_neurog2_mrc5_treatment_05dpt"
count_lines_confidence "smith_neurog2_mrc5_treatment_1dpt"
count_lines_confidence "smith_neurog2_mrc5_treatment_2dpt"
count_lines_confidence "vainorius_neurog2_mesc"
count_lines_confidence "pereira_neurog2_astrocytes"
count_lines_confidence "pereira_neurog2_astrocytes_yy+"
count_lines_confidence "pereira_neurog2_astrocytes_yy-"
count_lines_confidence "li_twist2_myoblast_dm_control"
count_lines_confidence "li_twist2_myoblast_dm_treatment"
count_lines_confidence "li_twist2_myoblast_gm_control"
count_lines_confidence "li_twist2_myoblast_gm_treatment"
count_lines_confidence "fan_twist1_eb_control"
count_lines_confidence "fan_twist1_eb_treatment"
count_lines_confidence "yu_twist1_mcf7_control"
count_lines_confidence "yu_twist1_mcf7_treatment"
count_lines_confidence "lee_twist1_bmsc_control"
count_lines_confidence "lee_twist1_bmsc_treatment"
count_lines_confidence "kim_twist1_hek_treatment_pcag"
count_lines_confidence "kim_twist1_hek_treatment_pcdna"
count_lines_confidence "mazzoni_olig2_mesc"
count_lines_confidence "costa_atoh1_mesc"
count_lines_confidence "liu_atoh8_lungcarcinoma"
count_lines_confidence "lin_mesp1_mesc_treatment_12h"
count_lines_confidence "lin_mesp1_mesc_treatment_24h"
count_lines_confidence "chalamalasetty_msgn1_eb"
count_lines_confidence "hershbach_myod1_mef"
count_lines_confidence "fong_myod1_p19"
count_lines_confidence "fong_myod1_mef"
count_lines_confidence "casey_myod1_mesc"
count_lines_confidence "lee_myod1_mef"
count_lines_confidence "lee_myod1_mesc"
count_lines_confidence "conerly_myod1_mef"
count_lines_confidence "manandhar_myod1_fibroblasts"
count_lines_confidence "conerly_myf5_mef"
count_lines_confidence "casey_ascl1_mesc"
count_lines_confidence "aydin_ascl1_eb_treatment_12h"
count_lines_confidence "aydin_ascl1_eb_treatment_48h"
count_lines_confidence "lee_ascl1_mesc"
count_lines_confidence "lee_ascl1_mef"
count_lines_confidence "wapinski_ascl1_mef"
count_lines_confidence "wapinski_ascl1_npc"
count_lines_confidence "park_ascl1_glioblastoma_control"
count_lines_confidence "park_ascl1_glioblastoma_treatment"
count_lines_confidence "vainorius_ascl1_mesc"
count_lines_confidence "woods_ascl1_neuroblastoma_wt31_treatment"
count_lines_confidence "woods_ascl1_neuroblastoma_wt51_control"
count_lines_confidence "woods_ascl1_neuroblastoma_wt51_treatment"
count_lines_confidence "wang_ascl1_gi-men"
count_lines_confidence "joung_ascl1_hesc"
count_lines_confidence "raposo_ascl1_ns5"
count_lines_confidence "casey_ascl2_mesc"
count_lines_confidence "liu_ascl2_cd4_control"
count_lines_confidence "liu_ascl2_cd4_treatment"
count_lines_confidence "jain_tcf4_sudhl"
count_lines_confidence "jain_tcf4_tmd8"
count_lines_confidence "lorenzin_myc_u2os_control"
count_lines_confidence "lorenzin_myc_u2os_treatment"
count_lines_confidence "soufi_myc_bj_control"
count_lines_confidence "soufi_myc_bj_treatment"
count_lines_confidence "lin_myc_p493-6_control"
count_lines_confidence "lin_myc_p493-6_treatment_1h"
count_lines_confidence "lin_myc_p493-6_treatment_24h"
count_lines_confidence "see_myc_u2os_lowmyc"
count_lines_confidence "see_myc_u2os_highmyc"
count_lines_confidence "walz_myc_u2os_control"
count_lines_confidence "walz_myc_u2os_treatment"
count_lines_confidence "kress_myc_liver_control"
count_lines_confidence "kress_myc_liver_treatment"
count_lines_confidence "barfeld_myc_lncap_control"
count_lines_confidence "barfeld_myc_lncap_treatment"
count_lines_confidence "croci_myc_liver_control"
count_lines_confidence "croci_myc_liver_treatment"
count_lines_confidence "croci_myc_mef"
count_lines_confidence "sabo_myc_mef_control"
count_lines_confidence "sabo_myc_mef_treatment"
count_lines_confidence "sabo_myc_lymphoblastoma_lowmyc"
count_lines_confidence "sabo_myc_lymphoblastoma_highmyc"
count_lines_confidence "sabo_myc_lymphoblastoma_control"
count_lines_confidence "sabo_myc_lymphoblastoma_treatment_1h"
count_lines_confidence "sabo_myc_lymphoblastoma_treatment_24h"
count_lines_confidence "depretis_myc_mef_control"
count_lines_confidence "depretis_myc_mef_treatment_10min"
count_lines_confidence "depretis_myc_mef_treatment_20min"
count_lines_confidence "depretis_myc_mef_treatment_30min"
count_lines_confidence "depretis_myc_mef_treatment_2h"
count_lines_confidence "depretis_myc_mef_treatment_4h"
count_lines_confidence "muthalagu_myc_mcf10a"
count_lines_confidence "tameire_myc_colorectaladenocarcinoma"
count_lines_confidence "jaenicke_myc_imec"
count_lines_confidence "liang_myc_h2171"
count_lines_confidence "thomas_myc_hek_control"
count_lines_confidence "thomas_myc_hek_treatment"
count_lines_confidence "jung_myc_u2os_control"
count_lines_confidence "jung_myc_u2os_treatment"
count_lines_confidence "zeid_mycn_shep_control"
count_lines_confidence "zeid_mycn_shep_treatment_2h"
count_lines_confidence "zeid_mycn_shep_treatment_6h"
count_lines_confidence "upton_mycn_lan5"
count_lines_confidence "upton_mycn_nb1643"
count_lines_confidence "upton_mycn_cogn415"
count_lines_confidence "bosse_mycn_ngp"
count_lines_confidence "bosse_mycn_kelly"
count_lines_confidence "bosse_mycn_nb1643"
count_lines_confidence "herold_mycn_shep_control"
count_lines_confidence "herold_mycn_shep_treatment"
count_lines_confidence "neikes_mycmax_mcf7_treatment_0001nm"
count_lines_confidence "neikes_mycmax_mcf7_treatment_0010nm"
count_lines_confidence "neikes_mycmax_mcf7_treatment_0100nm"
count_lines_confidence "neikes_mycmax_mcf7_treatment_1000nm"
count_lines_confidence "louphrasitthiphol_mitf_melanoma_control"
count_lines_confidence "louphrasitthiphol_mitf_melanoma_treatment"
count_lines_confidence "weber_hey1_cardiomyocytes_control"
count_lines_confidence "weber_hey1_cardiomyocytes_treatment"
count_lines_confidence "weber_hey1_mesc_control"
count_lines_confidence "weber_hey1_mesc_treatment"
count_lines_confidence "weber_hey2_cardiomyocytes_control"
count_lines_confidence "weber_hey2_cardiomyocytes_treatment"
count_lines_confidence "weber_hey2_mesc_control"
count_lines_confidence "weber_hey2_mesc_treatment"
count_lines_confidence "shang_hes1_mesc"
count_lines_confidence "sugita_hes1_chrondrocytes"
count_lines_confidence "letourneau_sim2_mesc_a6"
count_lines_confidence "letourneau_sim2_mesc_b8"
count_lines_confidence "letourneau_sim2_mesc_c4"
count_lines_confidence "letourneau_sim2_mesc_eb3"
count_lines_confidence "gambardella_tfeb_hek_treatment_18h"
count_lines_confidence "gambardella_tfeb_hek_treatment_36h"
count_lines_confidence "gambardella_tfeb_hek_treatment_90h"
count_lines_confidence "tai-nagara_tfe3_hk-2"
count_lines_confidence "emming_bhlhe40_jurkat_control_clone1"
count_lines_confidence "emming_bhlhe40_jurkat_treatment_clone1"
count_lines_confidence "emming_bhlhe40_jurkat_control_clone2"
count_lines_confidence "emming_bhlhe40_jurkat_treatment_clone2"
paste <(cut -f1 line_counts.tsv) confidence_counts.txt <(cut -f2,3,4,5,6,7 line_counts.tsv) > peak_counts.tsv

import_shiva proneural/chip-seq/peak_counts.tsv Dropbox/induction

## crear carpetas para humano y para mouse

mkdir ~/proneural/chip-seq/human
mkdir ~/proneural/chip-seq/mouse

# Move specified confidence.bed files to the mouse directory
for file in matsuda_neurod1_microglia pataskar_neurod1_mesc fong_neurod2_p19 fong_neurod2_mef fong_neurod2_p19_control fong_neurod2_p19_treatment aydin_neurog2_eb_treatment_12h aydin_neurog2_eb_treatment_48h velasco_neurog2_eb_treatment_12h vainorius_neurog2_mesc pereira_neurog2_astrocytes pereira_neurog2_astrocytes_yy+ pereira_neurog2_astrocytes_yy- li_twist2_myoblast_dm_control li_twist2_myoblast_dm_treatment li_twist2_myoblast_gm_control li_twist2_myoblast_gm_treatment fan_twist1_eb_control fan_twist1_eb_treatment yu_twist1_mcf7_control yu_twist1_mcf7_treatment mazzoni_olig2_mesc costa_atoh1_mesc lin_mesp1_mesc_treatment_12h lin_mesp1_mesc_treatment_24h chalamalasetty_msgn1_eb hershbach_myod1_mef fong_myod1_p19 fong_myod1_mef casey_myod1_mesc lee_myod1_mef lee_myod1_mesc conerly_myod1_mef conerly_myf5_mef casey_ascl1_mesc aydin_ascl1_eb_treatment_12h aydin_ascl1_eb_treatment_48h lee_ascl1_mesc lee_ascl1_mef wapinski_ascl1_mef wapinski_ascl1_npc vainorius_ascl1_mesc raposo_ascl1_ns5 casey_ascl2_mesc liu_ascl2_cd4_control liu_ascl2_cd4_treatment kress_myc_liver_control kress_myc_liver_treatment croci_myc_liver_control croci_myc_liver_treatment croci_myc_mef depretis_myc_mef_control depretis_myc_mef_treatment_10min depretis_myc_mef_treatment_20min depretis_myc_mef_treatment_30min depretis_myc_mef_treatment_2h depretis_myc_mef_treatment_4h weber_hey1_cardiomyocytes_control weber_hey1_cardiomyocytes_treatment weber_hey1_mesc_control weber_hey1_mesc_treatment weber_hey2_cardiomyocytes_control weber_hey2_cardiomyocytes_treatment weber_hey2_mesc_control weber_hey2_mesc_treatment shang_hes1_mesc letourneau_sim2_mesc_a6 letourneau_sim2_mesc_b8 letourneau_sim2_mesc_c4 letourneau_sim2_mesc_eb3; do
  mv "${file}_confidence.bed" ~/proneural/chip-seq/mouse/
done

# las demas a human
mv *confidence.bed ~/proneural/chip-seq/human
